### ISSUE TITLE
Raise a type error when neos.Logout(true) called

### ISSUE THREAD

**Issue by threepipes** [PolyLogiX-Studio/Neos.js#53]
I got an error when I used neos.Logout(true)
error:
```
(node:697) UnhandledPromiseRejectionWarning: TypeError: this.CurrentSession.SessionToken is not a function
    at CloudXInterface.Logout (/home/myname/node_modules/@bombitmanbomb/neosjs/API.js:3274:47)
    at Neos.Logout (/home/myname/node_modules/@bombitmanbomb/neosjs/Neos.js:231:26)
    at /home/myname/work/neosjs/sample/sample01.js:5:10
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:697) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:697) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

source:
```javascript
const Neos = require('@bombitmanbomb/neosjs');
const neos = new Neos();

neos.Login(process.env.NEOS_USER, process.env.NEOS_PASS).then((session) => {
    neos.Logout(true);
})
```

Environment:
- Windows10 wsl2
- node v13.12.0

**Comment by bombitmanbomb** [comment]
Try passing false and see if the same error happens, the bullion is to notate a manual logout

**Comment by threepipes** [comment]
When passing false, I got another error.
```
Exception in PromiseRejectCallback:
/home/myname/node_modules/@bombitmanbomb/neosjs/API.js:3923
    });


RangeError: Maximum call stack size exceeded
Exception in PromiseRejectCallback:
/home/myname/node_modules/@bombitmanbomb/neosjs/API.js:3911
      return await this.GetFriends(this.CurrentUser.Id, userId);
                        ^

RangeError: Maximum call stack size exceeded
(node:732) UnhandledPromiseRejectionWarning: RangeError: Maximum call stack size exceeded
    at CloudXInterface.get CurrentUser [as CurrentUser] (/home/myname/node_modules/@bombitmanbomb/neosjs/API.js:2733:18)
    at CloudXInterface.GetFriends (/home/myname/node_modules/@bombitmanbomb/neosjs/API.js:3911:41)
    at CloudXInterface.GetFriends (/home/myname/node_modules/@bombitmanbomb/neosjs/API.js:3911:25)
    at CloudXInterface.GetFriends (/home/myname/node_modules/@bombitmanbomb/neosjs/API.js:3911:25)
    at CloudXInterface.GetFriends (/home/myname/node_modules/@bombitmanbomb/neosjs/API.js:3911:25)
    at CloudXInterface.GetFriends (/home/myname/node_modules/@bombitmanbomb/neosjs/API.js:3911:25)
    at CloudXInterface.GetFriends (/home/myname/node_modules/@bombitmanbomb/neosjs/API.js:3911:25)
    at CloudXInterface.GetFriends (/home/myname/node_modules/@bombitmanbomb/neosjs/API.js:3911:25)
    at CloudXInterface.GetFriends (/home/myname/node_modules/@bombitmanbomb/neosjs/API.js:3911:25)
    at CloudXInterface.GetFriends (/home/myname/node_modules/@bombitmanbomb/neosjs/API.js:3911:25)
(node:732) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:732) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by bombitmanbomb** [comment]
I think I know what is happening take a look at it.

**Comment by threepipes** [comment]
https://github.com/PolyLogiX-Studio/Neos.js/blob/master/API.js#L3274
Missing new line after this.CurrentSession.SessionToken?

**Comment by bombitmanbomb** [comment]
Correct, Missing `;`, is an async functions in a sync function

**Comment by bombitmanbomb** [comment]
the call stack error is you running logout, and the FriendManager trying to fetch friends without a check if logged in,

**Comment by bombitmanbomb** [comment]
I have fixed the logout and adding a catch to the friend manager. will be in the next patch.
