### ISSUE TITLE
Crash with Headless

### ISSUE THREAD

**Issue by RaithSphere** [PolyLogiX-Studio/Neos.js#62]
Keep having a crash when using the Headless system, I am not passing commands to it when this happens

 ```
ERROR
SyntaxError: Unexpected token_ in JSON at position 0
    at JSON.parse (<anonymous>)
    at /home/raith/test/node_modules/@bombitmanbomb/neosjs/API/HTTP_CLIENT.js:39:25
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async HTTP_CLIENT.SendAsync (/home/raith/test/node_modules/@bombitmanbomb/neosjs/API/HTTP_CLIENT.js:32:20)
    at async CloudXInterface.GetServerStatistics (/home/raith/test/node_modules/@bombitmanbomb/neosjs/API/CloudXInterface.js:1798:14)
    at async /home/raith/test/node_modules/@bombitmanbomb/neosjs/API/CloudXInterface.js:503:27
(node:25685) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 HeadlessResponse listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
FetchError: request to https://cloudxstorage.blob.core.windows.net/install/ServerResponse failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/home/raith/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (node:events:327:20)
    at TLSSocket.socketErrorListener (node:_http_client:478:9)
    at TLSSocket.emit (node:events:327:20)
    at emitErrorNT (node:internal/streams/destroy:194:8)
    at emitErrorCloseNT (node:internal/streams/destroy:159:3)
    at processTicksAndRejections (node:internal/process/task_queues:80:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}
TypeError: Cannot read property 'content-length' of undefined
    at /home/raith/test/node_modules/@bombitmanbomb/neosjs/API/CloudXInterface.js:1802:58
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async CloudXInterface.GetServerStatistics (/home/raith/test/node_modules/@bombitmanbomb/neosjs/API/CloudXInterface.js:1798:14)
    at async /home/raith/test/node_modules/@bombitmanbomb/neosjs/API/CloudXInterface.js:503:27
/home/raith/test/node_modules/@bombitmanbomb/neosjs/API/CloudXInterface.js:504
        if (cloudResult.IsOK) {
                        ^

TypeError: Cannot read property 'IsOK' of null
    at /home/raith/test/node_modules/@bombitmanbomb/neosjs/API/CloudXInterface.js:504:25
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
```

**Comment by bombitmanbomb** [comment]
I believe the endpoint changed for Server Statistics with the new CloudX updates, Does it crash Every time or just frequently?

**Comment by RaithSphere** [comment]
it's been crashing randomly the past few days, but i will pull the update for the CloudX updates now as i didn't see the latest updates, i will update again after that

**Comment by bombitmanbomb** [comment]
Every now and then that specific endpoint is restarting or doesnt respond and I dont know why, Will ask froox about it. On the meantime the next push will contain a catch for it.

**Comment by RaithSphere** [comment]
> Every now and then that specific endpoint is restarting or doesnt respond and I dont know why, Will ask froox about it. On the meantime the next push will contain a catch for it.

Okay thanks bombitmanbomb
