### ISSUE TITLE
Command Handler has a fit when you send it a Record Object

### ISSUE THREAD

**Issue by RoxyBoxxy** [PolyLogiX-Studio/Neos.js#64]

**Comment by bombitmanbomb** [comment]
Need more info.

**Comment by RoxyBoxxy** [comment]
```
xx Headless Client > TypeError: Record is not a constructor                                                                                                          x
xx Headless Client >     at Neos.<anonymous> (/home/roxyboxxy/neosbot/app.js:74:20)                                                                                  x
xx Headless Client >     at Neos.emit (events.js:314:20)                                                                                                             x
xx Headless Client >     at Events.<anonymous> (/home/roxyboxxy/neosbot/node_modules/.pnpm/@bombitmanbomb/neosjs@1.5.14/node_modules/@bombitmanbomb/neosjs/Neos.js:  x
xx Headless Client >     at Events.emit (events.js:314:20)                                                                                                           x
xx Headless Client >     at Neos.CloudXInterface.Messages.onMessageReceived (/home/roxyboxxy/neosbot/node_modules/.pnpm/@bombitmanbomb/neosjs@1.5.14/node_modules/@  x
xx Headless Client >     at /home/roxyboxxy/neosbot/node_modules/.pnpm/@bombitmanbomb/neosjs@1.5.14/node_modules/@bombitmanbomb/neosjs/API/MessageManager.js:119:44  x
xx Headless Client >     at runMicrotasks (<anonymous>)                                                                                                              x
xx Headless Client >     at processTicksAndRejections (internal/process/task_queues.js:97:5)                                                                         x
xx Headless Client >     at async /home/roxyboxxy/neosbot/node_modules/.pnpm/@bombitmanbomb/neosjs@1.5.14/node_modules/@bombitmanbomb/neosjs/API/MessageManager.js:  
```

**Comment by bombitmanbomb** [comment]
The last line which i need is cut off, Also the context you called in line 74 could be helpfull
