### ISSUE TITLE
FetchError: request

### ISSUE THREAD

**Issue by RaithSphere** [PolyLogiX-Studio/Neos.js#68]
Version 1.6.14

I know this one maybe down to my own problem but I am now getting this issue, again the server is just idle not doing anything, i do have another instance running which has also had this happen

/home/raith/test/node_modules/@bombitmanbomb/neosjs/API/CloudXInterface.js:311
    throw new Error(error);
          ^

Error: Error: FetchError: request to https://cloudxstorage.blob.core.windows.net/install/ServerResponse failed, reason: connect ECONNREFUSED 52.165.136.32:443
    at CloudXInterface.onError (/home/raith/test/node_modules/@bombitmanbomb/neosjs/API/CloudXInterface.js:311:11)
    at CloudXInterface.GetServerStatistics (/home/raith/test/node_modules/@bombitmanbomb/neosjs/API/CloudXInterface.js:1858:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async /home/raith/test/node_modules/@bombitmanbomb/neosjs/API/CloudXInterface.js:481:27

**Comment by bombitmanbomb** [comment]
The onError hook if not handled will throw an error,

Neos.on("error", (err)=>{})
