### ISSUE TITLE
Bug: Context Error

### ISSUE THREAD

**Issue by bombitmanbomb** [PolyLogiX-Studio/Neos.js#76]
`
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'CloudX' of undefined
    at CommandExtended.ParseArguments (/rbd/pnpm-volume/1ec37a32-93c3-449b-aa27-f26f8fb50fed/node_modules/.registry.npmjs.org/@bombitmanbomb/neosjs/1.7.5/node_modules/@bombitmanbomb/neosjs/Plugins/CommandExtended.js:123:40)
    at CommandHandler.Run (/rbd/pnpm-volume/1ec37a32-93c3-449b-aa27-f26f8fb50fed/node_modules/.registry.npmjs.org/@bombitmanbomb/neosjs/1.7.5/node_modules/@bombitmanbomb/neosjs/Plugins/CommandHandler.js:105:42)
    at CommandExtended.Run (/rbd/pnpm-volume/1ec37a32-93c3-449b-aa27-f26f8fb50fed/node_modules/.registry.npmjs.org/@bombitmanbomb/neosjs/1.7.5/node_modules/@bombitmanbomb/neosjs/Plugins/CommandExtended.js:324:27)`

**Comment by bombitmanbomb** [comment]
Fixed in 1.7.5
